### ISSUE TITLE
Firebase stream problem

### ISSUE THREAD

**Issue by MauzTrap** [mobizt/Firebase-Arduino-WiFiNINA#41]
Using mkr1010

Line 137 

Error:
Call of overloaded println(long long int) is ambiguous

I'm not nearly good enough to solve this one myself but I think it has something to do with trying to print "int64Data" based on the suggestions on Google for "how to print int64" help would be much appreciated.

Edit: it seems this problem is in all of the version 1.2.0 and up

**Comment by mobizt** [comment]
The library works fine and can compile in Arduino IDE (2.0 and older) and PlatformIO in VScode IDE for Arduino NANO 33 IoT, Arduino MKR WiFi 1010, Arduino MKR VIDOR 4000, Arduino Nano RP2040 Connect and Arduino UNO WiFi Rev.2

I already test it all.

About your compilation error, you should debug your code yourself by removing all third-party libraries from your code and in libraries folder which one of these libraries may contain the Print.h header file and cause the ambiguous function compilation error.

**Comment by MauzTrap** [comment]
Thats odd I'm using arduino ide 1.8.19 with no external libraries the only change I made was adding my wifi and server info in the definitions. I suppose I'll pull all the libraries out of the folder and see if it works

**Comment by MauzTrap** [comment]
I believe it was an outdated version of WIFINA library. Thank you for the help:)

**Comment by MauzTrap** [comment]
I'm having another problem. I'm running the basic and stream and it keeps saying bad request. I can run one of my older versions for stream and it works fine. Sorry to bother again just been a long time since I've done this stuff

**Comment by MauzTrap** [comment]
Is there a proper place to ask questions I dont wanna fill up this thread with unrelated questions I'm having a connection issues that I don't seem to have with my older versions of the "stream" that I wanna ask about

**Comment by mobizt** [comment]
You can ask the question [here](https://github.com/mobizt/Firebase-Arduino-WiFiNINA/discussions).

Please remember that the WiFiNINA firmware requires server SSL certificate verification for server authentication. The certificate can be expired or revoked on server side. You need to update the SSL certificate in case server connection problem.

The firmware and certificate update, see [this issue](https://github.com/mobizt/Firebase-Arduino-WiFiNINA/issues/18).

The only way for skipping server SSL certificate verification is [firmware modification](https://github.com/mobizt/Firebase-Arduino-WiFiNINA/issues/40).

**Comment by MauzTrap** [comment]
Ok thank you it seems that it only has issues with stream, the basic sketch works fine

**Comment by MauzTrap** [comment]
Just wanted to update for anyone reading. Adding Google ssl certificate made it work. It seems I have much to learn since the last time I did this. Thank you very much for the help. I'll post in discussions in the future since it seems the issues aren't actuslly with the coding itself

**Comment by mobizt** [comment]
Depending on the device you use, this library limits the size of payload response to store in FirebaseData object here which you can change it.

https://github.com/mobizt/Firebase-Arduino-WiFiNINA/blob/a74d6e49a662c677e8b8df12d5337c1ea4981612/src/Firebase.h#L44-L47

The large stream payload may not handle by the low memory devices then keep the data under the streaming path as small as possible.
